### ISSUE TITLE
Text truncated on mobile

### ISSUE THREAD

**Issue by silently** [ozwillo/ozwillo-doc#6]
discussion started on #1 with https://cloud.githubusercontent.com/assets/6223745/6246915/ae34e672-b776-11e4-8011-6b271e1ea68d.png

Proposal: fix truncation, and then disable user-scalable property.

**Comment by silently** [comment]
@vdachev it should be fixed now

**Comment by silently** [comment]
@vdachev can you confirm?

**Comment by vdachev** [comment]
@silently much better now. :)
